# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Custom Magic Space
description: > # this means to ignore newlines until "baseurl:"
  The world's best primer and reference sheet for creators of custom Magic: the Gathering cards.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.custommagic.space" # the base hostname & protocol for your site
permalink: pretty

# Build settings
markdown: kramdown